name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Log in to Docker Hub (replace secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build and push Docker images
      - name: Build & push backend image
        run: |
          docker build -t your_dockerhub_username/backend:latest -f backend/Dockerfile .
          docker push your_dockerhub_username/backend:latest

      - name: Build & push ML image
        run: |
          docker build -t your_dockerhub_username/ml_model:latest -f ml_model/Dockerfile .
          docker push your_dockerhub_username/ml_model:latest

      - name: Build & push frontend image
        run: |
          docker build -t your_dockerhub_username/frontend:latest -f frontend/Dockerfile .
          docker push your_dockerhub_username/frontend:latest